title: Epic Speeches Network
description: Direct speech in Greek and Latin epic, from Homer to Nonnus
theme: minima
author:
  name: Chris Forstall
  email: cforstall@mta.ca
contact_email: info@epicspeeches.net
header_pages:
  - dices.md
  - cfp.md
  - posts.md